name: Genera PDF al push su main

on:
  push:
    branches:
      - main

jobs:
  build-and-commit-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Verifica modifiche su file .tex
        id: tex-check
        run: |
          # Verifica se ci sono modifiche nei file .tex
          files_modified=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Modifiche trovate: $files_modified"
          
          # Se ci sono modifiche solo a file .tex, continua, altrimenti esce
          if echo "$files_modified" | grep -q '\.tex$'; then
            echo "Modificato un file .tex, procedo con la compilazione."
            echo "tex_modified=true" >> $GITHUB_OUTPUT
          else
            echo "Nessuna modifica ai file .tex, esco senza fare nulla."
            echo "tex_modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Interrompi se nessun .tex è stato modificato
        if: steps.tex-check.outputs.tex_modified == 'false'
        run: exit 0

      - name: Installazione di LaTeX (inclusa lingua italiana)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-italian \
            latexmk \
            rsync

      - name: Compilazione del file LaTeX in PDF
        run: |
          mkdir -p pdf_output
          rsync -a --include '*/' --exclude '*' chapters/ pdf_output/chapters/
          latexmk -pdf -output-directory=pdf_output -f main.tex

      - name: Configurazione di Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit e push del PDF generato
        run: |
          git add pdf_output/main.pdf
          git commit -m "Aggiornamento automatico del PDF dopo il push su main" || echo "Nessuna modifica da committare"
          git push

