name: Notify Telegram on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          COMMIT_MSG=$(git log -1 --pretty=%s)

          read -r -d '' MESSAGE <<EOF
          🔄 *Merge eseguito su \`main\`*
          📌 *Commit*: \`$SHORT_SHA\` — $COMMIT_MSG
          👤 *Autore*: $GITHUB_ACTOR
          EOF

          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            --data-urlencode chat_id=${TELEGRAM_CHAT_ID} \
            --data-urlencode message_thread_id=${TELEGRAM_THREAD_ID} \
            --data-urlencode text="$MESSAGE" \
            --data-urlencode parse_mode=Markdown
