name: Notify Telegram on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          COMMIT_MSG=$(git log -1 --pretty=%s)

          MESSAGE="🔄 *Merge eseguito su \`main\`*\n\
          📌 *Commit*: \`$SHORT_SHA\` — $COMMIT_MSG\n\
          👤 *Autore*: $GITHUB_ACTOR"

          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d message_thread_id=${TELEGRAM_THREAD_ID} \
            -d text="$MESSAGE" \
            -d parse_mode="MarkdownV2"
